stages:
  - tests
  - deploy
  - prepare
  - release

variables:
  ARTIFACT_NAME: "correoargentino"

.before_script_php_template: &before_script_php
  before_script:
    - bash ci/docker_install.sh > /dev/null
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - php composer.phar install

#php-cs-fixer-7-3:
#  <<: *before_script_php
#  image: php:7.3
#  stage: tests
#  script: |
#    php composer.phar install --dev
#    php composer.phar require prestashop/prestashop:1.7.8.5
#    php composer.phar require csa/guzzle-bundle:dev-compat-php
#    php -d memory_limit=-1 vendor/bin/php-cs-fixer fix
#
#phpstan-php-7-3:
#  <<: *before_script_php
#  variables:
#    _PS_ROOT_DIR_: /var/www/html/
#  image: prestashop/prestashop:1.7-7.3-apache
#  stage: tests
#  script: |
#    php composer.phar install --dev
#    php composer.phar global require phpstan/phpstan:^1.8
#    php -d memory_limit=-1 ~/.composer/vendor/bin/phpstan analyse --configuration=tests/phpstan/phpstan.neon


# Clean development files and zip content for the marketplace
deploy-artifact-release:
  <<: *before_script_php
  image: php:7.3
  stage: deploy
  script: |
    php composer.phar install --no-dev -o
    rm -rf node_modules
    rm -rf _dev
    rm -f .browserlistrc
    rm -f .eslintrc.js
    rm -f .postcssrc.js
    rm -f babel.config.js
    rm -f vue.config.js
    rm -f .package.json
    rm -f .package-lock.json
    rm -f .php_cs.dist
    rm -f .gitlab-ci.yml
    rm -f .editorconfig
    rm -f Makefile
    rm -f docker-compose.yml
    rm -rf .git
    rm -f .gitignore
    rm -rf tests
    rm -f composer.phar
    rm -f .php_cs.cache
    rm -f .php-cs-fixer.dist.php
    mkdir -p ../module
    mv * ../module
    mkdir -p $ARTIFACT_NAME
    mv ../module/* $ARTIFACT_NAME

  artifacts:
    name: $ARTIFACT_NAME
    paths:
      - $ARTIFACT_NAME

prepare_job:
  stage: prepare                                              # This stage must run before the release stage
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "EXTRA_DESCRIPTION=some message" >> variables.env  # Generate the EXTRA_DESCRIPTION and TAG environment variables
    - echo "TAG=v$(cat VERSION)" >> variables.env             # and append to the variables.env file
  artifacts:
    reports:
      dotenv: variables.env                                   # Use artifacts:reports:dotenv to expose the variables to other jobs

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
    tag_name: '$TAG'                                                 # variables must be defined elsewhere
    ref: '$CI_COMMIT_SHA'                                            # in the pipeline. For example, in the
